### PR TITLE
Fix self-signed cert support

### PR DESCRIPTION
**Pull request by partiallyordered**
Main change is to support self-signed certs correctly.

Also factored some assertions into an assertion function.

### CODE REVIEW

**Review by bushjames — COMMENTED** [review]
looks ok but I wonder if there is a cleaner way. is it possible to pass some additional args to openssl so it doesn't return a non zero result with a self signed cert?

**Comment by partiallyordered** [comment]
Although I'm not completely certain, it looks like openssl won't verify a self-signed cert that's not in the cert store. I did try this:
```sh
$ openssl verify cacert.pem -CAfile cacert.pem
CN = my-ca
error 18 at 0 depth lookup: self signed certificate
error cacert.pem: verification failed
Can't open -CAfile for reading, No such file or directory
140394647287104:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('-CAfile','r')
140394647287104:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load certificate
CN = my-ca
error 18 at 0 depth lookup: self signed certificate
error cacert.pem: verification failed
```
Which I _guess_ means not that the file wasn't there (as one of the messages indicates) but rather that it refused to use the self-signed cert as `CAfile` because it was self-signed. Though that seems odd. Anyway, I'm not going to read the source code for openssl, so I'll call that enough time wasted for now.

**Comment by bushjames** [comment]
it looks to me, given the above, that the command is not correctly formed. the `-CAfile` switch appears to be being interpretted as a filename itself.

**Comment by partiallyordered** [comment]
Ah correct, it is. Should've read the manual more carefully. Probably says something like `openssl verify [options] files` This works, it turns out:
```
$ openssl verify -CAfile cacert.pem -verbose cacert.pem
cacert.pem: OK
```
Will make a PR for this in the not-too-distant future.

**Pull request merged**
